---

name: Build

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  run-iris:
    name: Run IRIS Analysis
    runs-on: sonar-xs-public
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Run IRIS Analysis (local action)
        uses: ./run-iris
        with:
          primary_project_key: "SonarSource_unified-dogfooding-actions"
          primary_platform: "SQC-EU"
          shadow1_project_key: "SonarSource_unified-dogfooding-actions"
          shadow1_platform: "Next"
          shadow2_project_key: "SonarSource_unified-dogfooding-actions"
          shadow2_platform: "SQC-US"
