---

on:
  pull_request:

jobs:
  pre-commit:
    name: "pre-commit"
    runs-on: sonar-xs-public
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: SonarSource/ci-github-actions/config-npm@v1
      - uses: SonarSource/gh-action_pre-commit@2ddc0c7fdabce0adfaaa4075a17690972ed9961a # 1.2.0
        with:
          extra-args: >
            --from-ref=origin/${{ github.event.pull_request.base.ref }}
            --to-ref=${{ github.event.pull_request.head.sha }}
